#!/bin/bash

# Script to help diagnose AT&T router configuration
echo "=== AT&T Router Configuration Check ==="
echo ""

echo "Based on your router tabs, here's where to look for firewall rules:"
echo ""
echo "1. PACKET FILTER tab:"
echo "   - Look for 'Inbound Rules' or 'Access Control List'"
echo "   - This is where most firewall rules are configured"
echo ""
echo "2. NAT/GAMING tab:"
echo "   - Check your port 8082 forwarding rule"
echo "   - Look for checkbox like 'Allow through firewall' or 'Bypass firewall'"
echo ""
echo "3. SECURITY OPTIONS tab:"
echo "   - Look for 'Firewall Rules' or 'Access Control'"
echo "   - Check if there's a 'Default Deny' setting"
echo ""

echo "=== Common AT&T Router Firewall Settings ==="
echo ""
echo "Look for these specific settings:"
echo ""
echo "✓ Inbound Rules/ACL:"
echo "  - Should have ALLOW rule for TCP port 8082"
echo "  - Source: Any (0.0.0.0/0)"
echo "  - Destination: 192.168.1.143:8082"
echo ""
echo "✓ Port Forwarding:"
echo "  - External Port: 8082"
echo "  - Internal IP: 192.168.1.143"
echo "  - Internal Port: 8082"
echo "  - Protocol: TCP"
echo "  - Check for 'Firewall Exception' or 'Bypass' option"
echo ""
echo "✓ Default Firewall Policy:"
echo "  - Should NOT be 'Deny All' or 'Block All Incoming'"
echo "  - Should be 'Allow Established' or 'Default Allow'"
echo ""

echo "=== Why It Might Have Worked Before ==="
echo ""
echo "1. Router firmware update reset firewall rules"
echo "2. Port forwarding rule got deleted/recreated without firewall bypass"
echo "3. Someone changed firewall policy from 'Allow' to 'Deny'"
echo "4. Temporary 'Gaming Mode' or 'DMZ' was enabled before"
echo "5. Firewall rule got moved below a 'Deny All' rule"
echo ""

echo "=== Next Steps ==="
echo ""
echo "1. Check 'Packet Filter' tab for inbound rules"
echo "2. Look for your port 8082 rule in 'NAT/Gaming'"
echo "3. Check if there's a 'Bypass Firewall' option for port forwarding"
echo "4. Look for any 'Default Deny' or 'Block All' rules"
echo "5. If you find firewall rules, make sure port 8082 ALLOW rule is ABOVE any DENY rules"
