version: '3.8'

services:
  # Frontend React application for development
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
      - REACT_APP_DOCKER=false
      - REACT_APP_API_URL=http://localhost:3000
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    networks:
      - trading-network
    restart: unless-stopped

  # Backend API server for development
  backend:
    image: your-backend-image:latest  # Replace with your actual backend image
    # build:
    #   context: ../backend
    #   dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_URL=your_database_url_here
      - ANTHROPIC_API_KEY=your_anthropic_api_key_here
    networks:
      - trading-network
    restart: unless-stopped

networks:
  trading-network:
    driver: bridge 